#!/bin/bash
#SBATCH -A TG-SEE160002
#SBATCH -J particle-mpi16
#SBATCH -o particle-mpi16.stdout
#SBATCH -N 16 -n 16         
#SBATCH -p compute
#SBATCH --export=ALL
#SBATCH -t 00:10:00     
ibrun ./mpi -n 1000 -o mpi.txt
